# ClusterRole to use podsecuritypolicy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cart
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - cart
---
# Authorize all service accounts in namespace to use the podsecuritypolicy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cart
  namespace: cart
roleRef:
  kind: ClusterRole
  name: cart
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
